### PR TITLE
Rework so this can be used with lit-html.

### PR DESCRIPTION
**Pull request by coreyfarrell**
Sorry for posting an almost total rewrite.  I'd like to see if you are willing to merge this to become version 2.  I'm willing to switch lint from `xo` to something else if that can help get this merged.  Really my goal is not to fork your module.  I'm hoping I can either get these changes merged here, or if you are no longer using/maintaining this module I'd like to request transfer of the npm package.  Obviously being a breaking change this would never be released under version 1.x.  This babel plugin is still compatible with babel 6 though testing is updated to use babel 7.

The existing published module only supports 'default' exports.  Update
this component to support multiple types of imports:
* `import html from 'choo/html';`
* `import {html} from 'lit-html';`
* `import * as litHtml from 'lit-html';`

In these examples html-minifier will process templates given to `html`
for the first two examples, `litHtml.html` in the third example.

This also detects any situation where html-minifier deletes the place
where Javascript belongs.  For example `<!-- ${var} -->` or `<input
readonly="${var}">` if removeComments or collapseBooleanAttributes are
enabled, html-minifier will delete the spot we reinsert ${var}.

### CODE REVIEW

**Comment by goto-bus-stop** [comment]
Cool! This looks good to me, Ill add you as a collaborator when I get home tonight :)

**Comment by coreyfarrell** [comment]
I realized my update had removed support for `require`.  This has been reimplemented and tests updated to cover that part of the babel plugin (though `lit-html` for example would never be used via `require`).

**Comment by goto-bus-stop** [comment]
:+1: added you as a collaborator here and on the npm package, feel free to merge and publish!

**Comment by coreyfarrell** [comment]
Great, thanks!

**Comment by goto-bus-stop** [comment]
hey, thanks for keeping up maintenance here. i've not ended up using this package at all lately. would you mind if i transferred it to your github account so it's clear to people who's maintaining it now?

**Comment by coreyfarrell** [comment]
@goto-bus-stop That would be fine, please transfer to my @cfware organization.

**Comment by goto-bus-stop** [comment]
> You don’t have the permission to create repositories on cfware 

:( I think i have to transfer to you and then you can put it in cfware

(lol clicked the wrong link earlier)

**Comment by coreyfarrell** [comment]
I'm going to merge the PR I have and delete the fork I have under @coreyfarrell first.

**Comment by coreyfarrell** [comment]
OK please go ahead.

**Comment by goto-bus-stop** [comment]
> Transfer to coreyfarrell requested

thanks!

**Comment by coreyfarrell** [comment]
Looks like the move is successful (now to @cfware), thanks!

**Pull request merged**
